version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    restart: always
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/workers
    container_name: nginx

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    restart: always
    environment:
      PHP_IDE_CONFIG: "serverName=${XDEBUG_SERVER_NAME}"
    volumes:
      - ./app:/var/www/workers
    container_name: php

  postgres:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    restart: always
    ports:
      - ${POSTGRES_HOST_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - workers_db:/var/lib/postgresql/data:rw
    container_name: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_HOST_PORT}:8080

  composer:
    build:
      context: .
      dockerfile: php/composer.Dockerfile
    volumes:
      - ./app:/var/www/workers
    user: "${PUID}:${PGID}"

volumes:
  workers_db: